user-agent: *
disallow: /showcase.php/
disallow: /SendMailToFriend.php/
disallow: /SendMailToUser.php*
disallow: /myaccount/
disallow: /add_to_watchlist.php*
disallow: /report_item.php*
disallow: /NewItem/
disallow: /showitem/description/
disallow: /events/clicks
disallow: /auth/oauth/authorize
disallow: /login/auth
disallow: /offer/
disallow: /reco/api/v1/recommend*
disallow: /api/offer/item/counter.php*
disallow: /nl/_internal/selectedItemsContent*
disallow: *offerTypeBuyNow=1*
disallow: *offerTypeAuction=2*
disallow: *dostawa-kurier=1*
disallow: *dostawa-kurier-wieczor=1*
disallow: *dostawa-paczkomaty-inpost=1*
disallow: *dostawa-odbior-w-punkcie=1*
disallow: *dostawa-list=1*
disallow: *dostawa-paczka=1*
disallow: *dostawa-odbior-osobisty=1*
disallow: *dostawa-przesylka-elektroniczna=1*
disallow: *super-sprzedawca=1*
disallow: *monety=1*
disallow: *freeReturn=1*
disallow: *freeShipping=1*
disallow: *raty-zero=1*
disallow: *vat_invoice=1*
disallow: *ok=1*
disallow: *sm=1*
disallow: *startingTime=*
disallow: *price_from=*
disallow: *price_to=*
disallow: /login/
disallow: /explicit-content-warning.php*
disallow: /logowanie*
disallow: /cart-aggregator/
disallow: *freeDeliveryKids=1*
disallow: *dostawa-z-polski=*
disallow: *wyprzedaz=1*
disallow: *quantity=*
disallow: *oauth=*
disallow: *authorization_uri=*
disallow: *offerTypeAdvert=*
