User-agent: *
Disallow: /*/admin_link$
Disallow: /*/edit_label
Disallow: /*/one_click_form$
Disallow: /*/seller_actions$
Disallow: /*/tiny_link_to_cart$
Disallow: /*/user_manage$
Disallow: /account_settings/
Disallow: /api/v2/
Disallow: /ca/
Disallow: /campaign/
Disallow: /cart/
Disallow: /css/
Disallow: /components/products/related_deal/
Disallow: /fb_login
Disallow: /feed/feed.rss
Disallow: /gplus_login
Disallow: /js/
Disallow: /messages/
Disallow: /online/
Disallow: /palaver/
Disallow: /payment/
Disallow: /products/*/bookmarker$
Disallow: /products/*/recommended_bid_value
Disallow: /products/*_-*
Disallow: /products/load_image_gallery
Disallow: /product_discussion/vote/*
Disallow: /product_reviews/votes/*
Disallow: /product_reviews/vote/*
Disallow: /recomendations/*/owner_actions
Disallow: /system/
Disallow: /system2/
Disallow: /system3/
Disallow: /system4/
Disallow: /users/*/inactivity
Disallow: /users/login_menu
Disallow: /users/*/report
Disallow: /v2/

Sitemap: https://www.bukalapak.com/sitemap.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-0.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-1.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-2.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-3.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-4.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-5.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-6.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-7.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-8.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-9.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-10.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-11.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-12.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-13.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-14.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-15.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-16.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-17.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-18.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-19.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-20.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-21.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-22.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-23.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-24.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-25.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-26.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-27.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-28.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-29.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-30.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-31.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-32.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-33.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-34.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-35.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-36.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-37.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-38.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-39.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-40.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-41.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-42.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-43.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-44.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-45.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-46.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-47.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-48.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-49.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-50.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-51.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-52.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-53.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-54.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-55.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-56.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-57.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-58.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-59.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-60.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-61.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-62.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-63.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-64.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-65.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-66.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-67.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-68.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-69.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-70.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-71.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-72.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-73.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-74.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-75.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-76.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-77.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-78.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-79.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-80.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-81.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-82.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-83.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-84.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-85.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-86.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-87.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-88.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-89.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-90.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-91.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-92.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-93.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-94.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-95.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-96.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-97.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-98.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-99.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-100.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-101.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-102.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-103.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-104.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-105.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-106.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-107.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-tag-page-0.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-top-keyword-0.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-user-0.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-user-1.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-user-2.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-user-3.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-user-4.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-user-5.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-user-6.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-user-7.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-blog-0.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-bukareview-0.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-product-catalog-0.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-flight-route-0.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-bus-route-0.xml
    Sitemap: https://www.bukalapak.com/sitemap-index-train-route-0.xml

