User-agent: *
Disallow: *catalog/availability/
Disallow: */compare*
Disallow: *?filter=*
Disallow: *?priceFilter*
Disallow: *?sorting=*
Disallow: *&sorting=*
Disallow: *?storeId=*
Disallow: */catalog/packagepopup/
Disallow: */iows/*
Disallow: /ms/en_SE/
Disallow: */search/?query=*
Disallow: /webapp/wcs/stores/servlet/CreateUser
Disallow: /webapp/wcs/stores/servlet/IkeamsSearch
Disallow: /webapp/wcs/stores/servlet/InterestItemAdd
Disallow: /webapp/wcs/stores/servlet/InterestItemDisplay
Disallow: /webapp/wcs/stores/servlet/InterestItemDisplayView
Disallow: /webapp/wcs/stores/servlet/IrwCreateShoppingList
Disallow: /webapp/wcs/stores/servlet/IrwCreateShoppingListNoJS
Disallow: /webapp/wcs/stores/servlet/IrwDeleteShoppingList
Disallow: /webapp/wcs/stores/servlet/IrwEmailShoppingList
Disallow: /webapp/wcs/stores/servlet/IrwEmailShoppingListView
Disallow: /webapp/wcs/stores/servlet/IrwInterestItemAddByPartNumber
Disallow: /webapp/wcs/stores/servlet/IrwInterestItemDisplayNoJS
Disallow: /webapp/wcs/stores/servlet/IrwPrintShoppingList
Disallow: /webapp/wcs/stores/servlet/IrwRenameShoppingList
Disallow: /webapp/wcs/stores/servlet/IrwRenameShoppingListNoJS
Disallow: /webapp/wcs/stores/servlet/IrwShoppingListNoJS
Disallow: /webapp/wcs/stores/servlet/IrwUpdateShoppingList
Disallow: /webapp/wcs/stores/servlet/IrwWSCreateInterestList
Disallow: /webapp/wcs/stores/servlet/IrwWSDeleteInterestList
Disallow: /webapp/wcs/stores/servlet/IrwWSGetAllInterestLists
Disallow: /webapp/wcs/stores/servlet/IrwWSGetInterestList
Disallow: /webapp/wcs/stores/servlet/IrwWSInterestItemAdd
Disallow: /webapp/wcs/stores/servlet/IrwWSInterestItemDelete
Disallow: /webapp/wcs/stores/servlet/IrwWSKioskPrintShoppingList
Disallow: /webapp/wcs/stores/servlet/IrwWSOrderItemAdd
Disallow: /webapp/wcs/stores/servlet/IrwWSOrderItemDelete
Disallow: /webapp/wcs/stores/servlet/IrwWSOrderItemMoveToShoppingList
Disallow: /webapp/wcs/stores/servlet/IrwWSRenameInterestList
Disallow: /webapp/wcs/stores/servlet/LogonForm
Disallow: /webapp/wcs/stores/servlet/OrderItemAdd
Disallow: /webapp/wcs/stores/servlet/OrderItemAddByPartNumber
Disallow: /webapp/wcs/stores/servlet/OrderItemDisplay
Disallow: /webapp/wcs/stores/servlet/OrderItemDisplayViewShiptoAssoc
Disallow: /webapp/wcs/stores/servlet/OrderItemDisplayViewShiptoDsp
Disallow: /webapp/wcs/stores/servlet/OrderItemUpdate
Disallow: *OrderItemDisplay*
Disallow: *StockAvailSearchForm*
Noindex: *preferedui=desktop*
Noindex: */catalog/productAlternative/*
Noindex: */catalog/products/*bvroute=Review*
Noindex: */catalog/products/*bvtab*
Disallow: *preferedui=desktop*
Disallow: */catalog/productAlternative/
Disallow: */catalog/products/*bvroute=Review*
Disallow: */catalog/products/*bvtab*
Disallow: /webapp/wcs/stores/servlet/StockAvailSearchForm
Disallow: /ms/en_MA/
Disallow: /ma/en/
Disallow: /retail/
Disallow: /be/nl/ikea/module
Disallow: /be/fr/ikea/module
Disallow: *?krypto=*
Disallow: */ideas/tags/
Disallow: */search/?q=*
Disallow: */search/products/?q*
Noindex: *compare=
Noindex: *krypto=
Noindex: *max_price=
Noindex: *maxprice=
Noindex: *min_price=
Noindex: *minprice=
Noindex: *OrderItemDisplay=
Noindex: *partNumber=
Noindex: *preferedui=
Noindex: *priceFilter=
Noindex: *printView=
Noindex: *productid=
Noindex: *range_chapter=
Noindex: *range_subcategory=
Noindex: *StockAvailSearchForm=
Noindex: *tblang=
Noindex: *catalogId=

# NWP rules:
Disallow: /ie/en/retail/
Disallow: /ie/en/user/
Disallow: /ie/en/order/
Disallow: /ie/en/search/
Disallow: /ie/en/redirectservice/
Disallow: /ie/en/container/
Disallow: /ie/en/ikea/module/
Disallow: /gb/en/retail/
Disallow: /gb/en/user/
Disallow: /gb/en/order/
Disallow: /gb/en/search/
Disallow: /gb/en/redirectservice/
Disallow: /gb/en/container/
Disallow: /gb/en/ikea/module/
Disallow: /be/fr/retail/
Disallow: /be/fr/user/
Disallow: /be/fr/order/
Disallow: /be/fr/search/
Disallow: /be/fr/redirectservice/
Disallow: /be/fr/container/
Disallow: /be/fr/ikea/module/
Disallow: /be/nl/retail/
Disallow: /be/nl/user/
Disallow: /be/nl/order/
Disallow: /be/nl/search/
Disallow: /be/nl/redirectservice/
Disallow: /be/nl/container/
Disallow: /be/nl/ikea/module/
Disallow: /es/es/retail/
Disallow: /es/es/user/
Disallow: /es/es/order/
Disallow: /es/es/search/
Disallow: /es/es/redirectservice/
Disallow: /es/es/container/
Disallow: /es/es/ikea/module/
Disallow: /es/en/retail/
Disallow: /es/en/user/
Disallow: /es/en/order/
Disallow: /es/en/search/
Disallow: /es/en/redirectservice/
Disallow: /es/en/container/
Disallow: /es/en/ikea/module/
Disallow: /ms/en_us/usearch/

Sitemap: https://www.ikea.com/domainwide-sitemaps/ow-index.xml
Sitemap: https://www.ikea.com/domainwide-sitemaps/index.xml