User-agent: *
Disallow: /Ajax/
Disallow: /ajaxloader/
Disallow: /Forms/
Disallow: /FullStory/
Disallow: /MasterPages/
Disallow: /Pages/
Disallow: /Setup/
Disallow: /Temp/
Disallow: /WebServices/
Disallow: /WebTasks/
Disallow: /Widgets/
Disallow: /*.asp$
Disallow: /*.aspx$
Allow: /

Sitemap: http://jamnews.com/sitemap.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap1.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap2.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap3.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap4.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap5.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap6.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap7.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap8.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap9.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap10.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap11.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap12.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap13.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap14.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap15.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap16.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap17.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap18.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap19.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap20.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap21.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap22.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap23.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap24.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap25.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap26.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap27.xml
Sitemap: http://jamnews.com/SiteMaps/sitemap28.xmlSitemap: http://jamnews.com/SiteMaps/sitemap29.xml
