User-agent: nutch
Allow: /

User-Agent: *
Allow: /
Disallow: /ru/s_m_business/bankingservice/partners_terms
Disallow: /ru/person/bank_cards/prepaid
Disallow: /ru/errors
Disallow: */sb-portal-com/*
Disallow: /ru/search
Disallow: /ru/person/sbpremier/services/distant/inner_apps
Disallow: /unique/*
Disallow: /ru/person/sb_premier/paket_uslug/akcia_faq
Disallow: /ru/person/digift
Disallow: /person/test/*
Disallow: /new_page/*
Disallow: /ru/s_m_business/svoe_delo/form
Disallow: /ru/person/familybank/security-island-sbol
Disallow: /ru/person/bank_cards/debit/gold-card/ab
Disallow: /ru/person/bank_cards/debit/gold-pg/ab
Disallow: /ru/person/bank_cards/credit/mastercard/ab
Disallow: /ru/person/sb1/rental_business_fund
Disallow: /ru/person/dist_services/inner_apps/qr-code
Disallow: /sb1/visatt_sbol
Disallow: /ru/person/sb1/vkladvip
Disallow: /sb1vkld
Disallow: /ru/person/sb1/vkladsbol
Disallow: /vkldusdv
Disallow: /ru/person/sb1/vkladusdvip
Disallow: /ru/person/sb1/vkladusd
Disallow: /vkldusd
Disallow: /ru/person/sb1/vkladusdsbol
Disallow: /vkldusdvip
Disallow: /promo/mastercardgold
Disallow: /ru/person/bank_cards/debit/litecard
Disallow: /ab3
Disallow: /ru/person/sb_premier/travel
Disallow: /promo/bonds_vsp
Disallow: /ru/person/sb1/indexmoex
Disallow: /cc_cib
Disallow: /common/img/uploaded/pdf/vr/*
Disallow: /ru/s_m_business/form/self
Disallow: /ru/s_m_business/form/momentum
Disallow: /ru/s_m_business/bankingservice/rko/smartterminal/iframe_evotor-buy
Disallow: /ru/s_m_business/bankingservice/rko/smartterminal/iframe_evotor-rent
Disallow: /ru/s_m_business/bankingservice/cards/iframe_bk
Disallow: /ru/s_m_business/cash-ins
Disallow: /ru/s_m_business/bankingservice/cards/corporatecards/cashback
Disallow: /ru/s_m_business/bankingservice/cards/corporatecards/cashback10
Disallow: /ru/s_m_business/bankingservice/cards/corporatecards/cashback10visa
Disallow: /ru/s_m_business/bankingservice/cards/credit-businesscards/form
Disallow: /ru/s_m_business/bankingservice/cards/premium-businesscards/form
Disallow: /ru/s_m_business/e-commerce/website
Disallow: /ru/s_m_business/e-commerce/card
Disallow: /ru/s_m_business/e-commerce/torgovlya
Disallow: /ru/s_m_business/e-commerce/internet-aquiring
Disallow: /ru/s_m_business/e-commerce/jurist
Disallow: /ru/s_m_business/e-commerce/evotor-buy
Disallow: /ru/s_m_business/e-commerce/mobterminal-aquiring
Disallow: /ru/s_m_business/e-commerce/open-account
Disallow: /ru/s_m_business/e-commerce/solomoto
Disallow: /ru/s_m_business/e-commerce/crm
Disallow: /ru/s_m_business/bankingservice/moya_torgovlya/iframe_moya_torgovlya
Disallow: /ru/s_m_business/svoe_delo/form
Disallow: /ru/s_m_business/svoe_delo/accounting
Disallow: /ru/s_m_business/svoe_delo/jurist
Disallow: /ru/s_m_business/svoe_delo/crm
Disallow: /ru/s_m_business/svoe_delo/evotor_buy
Disallow: /ru/s_m_business/svoe_delo/solomoto
Disallow: /common/img/uploaded/redirected/test/*
Disallow: /common/img/uploaded/redirected/s_m_business/testsvoedelo
Disallow: /uploaded/redirected/test/corporatecards
Disallow: /ru/s_m_business/testhelp-business
Disallow: /ru/s_m_business/form/unsubscribe
Disallow: /ru/s_m_business/bankingservice/cards/testcorporatecards
Disallow: /ru/s_m_business/bankingservice/cards/testsalaryproject
Disallow: /ru/s_m_business/testbk_main
Disallow: /ru/s_m_business/bankingservice/cards/testcorporatecards
Disallow: /ru/s_m_business/testcompliance
Disallow: /ru/s_m_business/testnewbusiness
Disallow: /ru/s_m_business/testsfb
Disallow: /ru/s_m_business/testsbbol
Disallow: /ru/s_m_business/testbox
Disallow: /ru/s_m_business/bankingservice/testacquiring_total
Disallow: /teststart 
Disallow: /testevo
Disallow: /testmain
Disallow: /testonlinecredit
Disallow: /testmbf 
Disallow: /testcomm
Disallow: /testsvoedelo
Disallow: /common/img/uploaded/files/pdf/s_m_business/noindex/*
Disallow: /ru/s_m_business/test/*
Disallow: /ru/promo/army
Disallow: /common/img/uploaded/redirected/acquiring
Disallow: /ru/s_m_business/products/insurance/dms
Disallow: /ru/person/credits/money/ab_consumer_unsecured
Disallow: /common/img/uploaded/redirected/person/sb1/short/vi
Disallow: /self_lawyer
Disallow: /self_site
Disallow: /self_online
Disallow: /self_faq
Disallow: /sb1/vi
Disallow: /ru/person/promo/tp_szb
Disallow: /ru/legal/test/*
Disallow: /sb1/ob
Disallow: /common/img/uploaded/redirected/person/sb1/short/ob
Disallow: /common/img/uploaded/files/pdf/legal/ovs/zayavlenie_o_zakrytii_raschetnogo_bankovskogo_scheta.zip
Disallow: /ru/s_m_business/mmb/1
Disallow: /ru/s_m_business/mmb/2
Disallow: /ru/s_m_business/mmb/3
Disallow: /common/img/uploaded/files/pdf/legal/ovs/zayavlenie_o_zakrytii_raschetnogo_bankovskogo_scheta.pdf
Disallow: /sb1/*
Disallow: /common/img/uploaded/redirected/person/sb1/short/*
Disallow: /promo/firsttalk/ftart/*
Disallow: /promo/sberparents
Disallow: /promo/sberparents2
Disallow: /promo/sberparents3
Disallow: /promo/sb1/*
Disallow: /ru/s_m_business/bpa
Disallow: /ru/person/contributions/deposits/gvozdica
Disallow: /ru/person/contributions/deposits/benefit
Disallow: /ru/person/contributions/deposits/no-passport
Disallow: /ru/person/contributions/deposits/record
Disallow: /ru/person/contributions/deposits/onlike
Disallow: /ru/person/contributions/close_deposits/benefit
Disallow: /ru/person/contributions/close_deposits/multi_currency
Disallow: /ru/person/contributions/close_deposits/inter
Disallow: /promo/pobeda6/
Disallow: /promo/gvozdika/
Disallow: /promo/prosto7/
Disallow: /promo/memory
Disallow: /ru/person/bank_cards/debit/newclient
Disallow: /common/img/uploaded/redirected/person/bank_cards/debet/newclient
Disallow: /ru/person/sberkids/faq_parents
Disallow: /ru/person/sberkids/faq_kids
Disallow: /ru/promo/paket_zarplatny
Disallow: /common/img/uploaded/redirected/person/promo/paket_zarplatny/
Disallow: /ru/person/bank_inshure/insuranceprogram/life/dszhkk
Disallow: /dszhkk
Disallow: /ru/support-test
Disallow: /ru/support-test/about_card-test
Disallow: /sms/*
Disallow: /common/img/uploaded/files/sms/*
Disallow: /ru/person/credits/money/consumer

User-Agent: GoogleBot
Allow: /
Disallow: /ru/errors
Disallow: */sb-portal-com/*
Disallow: /ru/search
Disallow: /ru/s_m_business/bankingservice/partners_terms
Disallow: /ru/person/bank_cards/prepaid
Disallow: /unique/*
Disallow: /ru/person/sb_premier/paket_uslug/akcia_faq
Disallow: /ru/person/digift
Disallow: /person/test/*
Disallow: /new_page/*
Disallow: /ru/s_m_business/svoe_delo/form
Disallow: /ru/person/familybank/security-island-sbol
Disallow: /ru/person/bank_cards/debit/gold-card/ab
Disallow: /ru/person/bank_cards/debit/gold-pg/ab
Disallow: /ru/person/bank_cards/credit/mastercard/ab
Disallow: /ru/person/sb1/rental_business_fund
Disallow: /ru/person/dist_services/inner_apps/qr-code
Disallow: /sb1/visatt_sbol
Disallow: /ru/person/sb1/vkladvip
Disallow: /sb1vkld
Disallow: /ru/person/sb1/vkladsbol
Disallow: /vkldusdv
Disallow: /ru/person/sb1/vkladusdvip
Disallow: /ru/person/sb1/vkladusd
Disallow: /vkldusd
Disallow: /ru/person/sb1/vkladusdsbol
Disallow: /vkldusdvip
Disallow: /promo/mastercardgold
Disallow: /ru/person/bank_cards/debit/litecard
Disallow: /ab3
Disallow: /ru/person/sb_premier/travel
Disallow: /promo/bonds_vsp
Disallow: /ru/person/sb1/indexmoex
Disallow: /cc_cib
Disallow: /common/img/uploaded/pdf/vr/*
Disallow: /ru/s_m_business/form/self
Disallow: /ru/s_m_business/form/momentum
Disallow: /ru/s_m_business/bankingservice/rko/smartterminal/iframe_evotor-buy
Disallow: /ru/s_m_business/bankingservice/rko/smartterminal/iframe_evotor-rent
Disallow: /ru/s_m_business/bankingservice/cards/iframe_bk
Disallow: /ru/s_m_business/cash-ins
Disallow: /ru/s_m_business/bankingservice/cards/corporatecards/cashback
Disallow: /ru/s_m_business/bankingservice/cards/corporatecards/cashback10
Disallow: /ru/s_m_business/bankingservice/cards/corporatecards/cashback10visa
Disallow: /ru/s_m_business/bankingservice/cards/credit-businesscards/form
Disallow: /ru/s_m_business/bankingservice/cards/premium-businesscards/form
Disallow: /ru/s_m_business/e-commerce/website
Disallow: /ru/s_m_business/e-commerce/card
Disallow: /ru/s_m_business/e-commerce/torgovlya
Disallow: /ru/s_m_business/e-commerce/internet-aquiring
Disallow: /ru/s_m_business/e-commerce/jurist
Disallow: /ru/s_m_business/e-commerce/evotor-buy
Disallow: /ru/s_m_business/e-commerce/mobterminal-aquiring
Disallow: /ru/s_m_business/e-commerce/open-account
Disallow: /ru/s_m_business/e-commerce/solomoto
Disallow: /ru/s_m_business/e-commerce/crm
Disallow: /ru/s_m_business/bankingservice/moya_torgovlya/iframe_moya_torgovlya
Disallow: /ru/s_m_business/svoe_delo/form
Disallow: /ru/s_m_business/svoe_delo/accounting
Disallow: /ru/s_m_business/svoe_delo/jurist
Disallow: /ru/s_m_business/svoe_delo/crm
Disallow: /ru/s_m_business/svoe_delo/evotor_buy
Disallow: /ru/s_m_business/svoe_delo/solomoto
Disallow: /common/img/uploaded/redirected/test/*
Disallow: /common/img/uploaded/redirected/s_m_business/testsvoedelo
Disallow: /uploaded/redirected/test/corporatecards
Disallow: /ru/s_m_business/testhelp-business
Disallow: /ru/s_m_business/form/unsubscribe
Disallow: /ru/s_m_business/bankingservice/cards/testcorporatecards
Disallow: /ru/s_m_business/bankingservice/cards/testsalaryproject
Disallow: /ru/s_m_business/testbk_main
Disallow: /ru/s_m_business/bankingservice/cards/testcorporatecards
Disallow: /ru/s_m_business/testcompliance
Disallow: /ru/s_m_business/testnewbusiness
Disallow: /ru/s_m_business/testsfb
Disallow: /ru/s_m_business/testsbbol
Disallow: /ru/s_m_business/testbox
Disallow: /ru/s_m_business/bankingservice/testacquiring_total
Disallow: /teststart 
Disallow: /testevo
Disallow: /testmain
Disallow: /testonlinecredit
Disallow: /testmbf 
Disallow: /testcomm
Disallow: /testsvoedelo
Disallow: /common/img/uploaded/files/pdf/s_m_business/noindex/*
Disallow: /ru/s_m_business/test/*
Disallow: /ru/promo/army
Disallow: /common/img/uploaded/redirected/acquiring
Disallow: /ru/s_m_business/products/insurance/dms
Disallow: /ru/person/credits/money/ab_consumer_unsecured
Disallow: /common/img/uploaded/redirected/person/sb1/short/vi
Disallow: /self_lawyer
Disallow: /self_site
Disallow: /self_online
Disallow: /self_faq
Disallow: /sb1/vi
Disallow: /ru/person/promo/tp_szb
Disallow: /ru/legal/test/*
Disallow: /sb1/ob
Disallow: /common/img/uploaded/redirected/person/sb1/short/ob
Disallow: /common/img/uploaded/files/pdf/legal/ovs/zayavlenie_o_zakrytii_raschetnogo_bankovskogo_scheta.zip
Disallow: /ru/s_m_business/mmb/1
Disallow: /ru/s_m_business/mmb/2
Disallow: /ru/s_m_business/mmb/3
Disallow: /common/img/uploaded/files/pdf/legal/ovs/zayavlenie_o_zakrytii_raschetnogo_bankovskogo_scheta.pdf
Disallow: /sb1/*
Disallow: /common/img/uploaded/redirected/person/sb1/short/*
Disallow: /promo/firsttalk/ftart/*
Disallow: /promo/sberparents
Disallow: /promo/sberparents2
Disallow: /promo/sberparents3
Disallow: /promo/sb1/*
Disallow: /ru/s_m_business/bpa
Disallow: /ru/person/contributions/deposits/gvozdica
Disallow: /ru/person/contributions/deposits/benefit
Disallow: /ru/person/contributions/deposits/no-passport
Disallow: /ru/person/contributions/deposits/record
Disallow: /ru/person/contributions/deposits/onlike
Disallow: /ru/person/contributions/close_deposits/benefit
Disallow: /ru/person/contributions/close_deposits/multi_currency
Disallow: /ru/person/contributions/close_deposits/inter
Disallow: /promo/pobeda6/
Disallow: /promo/gvozdika/
Disallow: /promo/prosto7/
Disallow: /promo/memory
Disallow: /ru/person/bank_cards/debit/newclient
Disallow: /common/img/uploaded/redirected/person/bank_cards/debet/newclient
Disallow: /ru/person/sberkids/faq_parents
Disallow: /ru/person/sberkids/faq_kids
Disallow: /ru/promo/paket_zarplatny
Disallow: /common/img/uploaded/redirected/person/promo/paket_zarplatny/
Disallow: /ru/person/bank_inshure/insuranceprogram/life/dszhkk
Disallow: /dszhkk
Disallow: /ru/support-test
Disallow: /ru/support-test/about_card-test
Disallow: /sms/*
Disallow: /common/img/uploaded/files/sms/*
Disallow: /ru/person/credits/money/consumer

User-Agent: Yandex
Disallow: /ru/errors
Disallow: */sb-portal-com/*
Disallow: /ru/search
Disallow: /ru/s_m_business/bankingservice/partners_terms
Disallow: /ru/person/bank_cards/prepaid
Disallow: /unique/*
Disallow: /ru/person/sb_premier/paket_uslug/akcia_faq
Disallow: /ru/person/digift
Disallow: /person/test/*
Disallow: /new_page/*
Disallow: /ru/s_m_business/svoe_delo/form
Disallow: /ru/person/familybank/security-island-sbol
Disallow: /ru/person/bank_cards/debit/gold-card/ab
Disallow: /ru/person/bank_cards/debit/gold-pg/ab
Disallow: /ru/person/bank_cards/credit/mastercard/ab
Disallow: /ru/person/sb1/rental_business_fund
Disallow: /ru/person/dist_services/inner_apps/qr-code
Disallow: /sb1/visatt_sbol
Disallow: /ru/person/sb1/vkladvip
Disallow: /sb1vkld
Disallow: /ru/person/sb1/vkladsbol
Disallow: /vkldusdv
Disallow: /ru/person/sb1/vkladusdvip
Disallow: /ru/person/sb1/vkladusd
Disallow: /vkldusd
Disallow: /ru/person/sb1/vkladusdsbol
Disallow: /vkldusdvip
Disallow: /promo/mastercardgold
Disallow: /ru/person/bank_cards/debit/litecard
Disallow: /ab3
Disallow: /ru/person/sb_premier/travel
Disallow: /promo/bonds_vsp
Disallow: /ru/person/sb1/indexmoex
Disallow: /cc_cib
Disallow: /common/img/uploaded/pdf/vr/*
Disallow: /ru/s_m_business/form/self
Disallow: /ru/s_m_business/form/momentum
Disallow: /ru/s_m_business/bankingservice/rko/smartterminal/iframe_evotor-buy
Disallow: /ru/s_m_business/bankingservice/rko/smartterminal/iframe_evotor-rent
Disallow: /ru/s_m_business/bankingservice/cards/iframe_bk
Disallow: /ru/s_m_business/cash-ins
Disallow: /ru/s_m_business/bankingservice/cards/corporatecards/cashback
Disallow: /ru/s_m_business/bankingservice/cards/corporatecards/cashback10
Disallow: /ru/s_m_business/bankingservice/cards/corporatecards/cashback10visa
Disallow: /ru/s_m_business/bankingservice/cards/credit-businesscards/form
Disallow: /ru/s_m_business/bankingservice/cards/premium-businesscards/form
Disallow: /ru/s_m_business/e-commerce/website
Disallow: /ru/s_m_business/e-commerce/card
Disallow: /ru/s_m_business/e-commerce/torgovlya
Disallow: /ru/s_m_business/e-commerce/internet-aquiring
Disallow: /ru/s_m_business/e-commerce/jurist
Disallow: /ru/s_m_business/e-commerce/evotor-buy
Disallow: /ru/s_m_business/e-commerce/mobterminal-aquiring
Disallow: /ru/s_m_business/e-commerce/open-account
Disallow: /ru/s_m_business/e-commerce/solomoto
Disallow: /ru/s_m_business/e-commerce/crm
Disallow: /ru/s_m_business/bankingservice/moya_torgovlya/iframe_moya_torgovlya
Disallow: /ru/s_m_business/svoe_delo/form
Disallow: /ru/s_m_business/svoe_delo/accounting
Disallow: /ru/s_m_business/svoe_delo/jurist
Disallow: /ru/s_m_business/svoe_delo/crm
Disallow: /ru/s_m_business/svoe_delo/evotor_buy
Disallow: /ru/s_m_business/svoe_delo/solomoto
Disallow: /common/img/uploaded/redirected/test/*
Disallow: /common/img/uploaded/redirected/s_m_business/testsvoedelo
Disallow: /uploaded/redirected/test/corporatecards
Disallow: /ru/s_m_business/testhelp-business
Disallow: /ru/s_m_business/form/unsubscribe
Disallow: /ru/s_m_business/bankingservice/cards/testcorporatecards
Disallow: /ru/s_m_business/bankingservice/cards/testsalaryproject
Disallow: /ru/s_m_business/testbk_main
Disallow: /ru/s_m_business/bankingservice/cards/testcorporatecards
Disallow: /ru/s_m_business/testcompliance
Disallow: /ru/s_m_business/testnewbusiness
Disallow: /ru/s_m_business/testsfb
Disallow: /ru/s_m_business/testsbbol
Disallow: /ru/s_m_business/testbox
Disallow: /ru/s_m_business/bankingservice/testacquiring_total
Disallow: /teststart 
Disallow: /testevo
Disallow: /testmain
Disallow: /testonlinecredit
Disallow: /testmbf 
Disallow: /testcomm
Disallow: /testsvoedelo
Disallow: /common/img/uploaded/files/pdf/s_m_business/noindex/*
Disallow: /ru/s_m_business/test/*
Disallow: /ru/promo/army
Disallow: /common/img/uploaded/redirected/acquiring
Disallow: /ru/s_m_business/products/insurance/dms
Disallow: /ru/person/credits/money/ab_consumer_unsecured
Disallow: /common/img/uploaded/redirected/person/sb1/short/vi
Disallow: /self_lawyer
Disallow: /self_site
Disallow: /self_online
Disallow: /self_faq
Disallow: /sb1/vi
Disallow: /ru/person/promo/tp_szb
Disallow: /ru/legal/test/*
Disallow: /sb1/ob
Disallow: /common/img/uploaded/redirected/person/sb1/short/ob
Disallow: /common/img/uploaded/files/pdf/legal/ovs/zayavlenie_o_zakrytii_raschetnogo_bankovskogo_scheta.zip
Disallow: /ru/s_m_business/mmb/1
Disallow: /ru/s_m_business/mmb/2
Disallow: /ru/s_m_business/mmb/3
Disallow: /common/img/uploaded/files/pdf/legal/ovs/zayavlenie_o_zakrytii_raschetnogo_bankovskogo_scheta.pdf
Disallow: /sb1/*
Disallow: /common/img/uploaded/redirected/person/sb1/short/*
Disallow: /promo/firsttalk/ftart/*
Disallow: /promo/sberparents
Disallow: /promo/sberparents2
Disallow: /promo/sberparents3
Disallow: /promo/sb1/*
Disallow: /ru/s_m_business/bpa
Disallow: /ru/person/contributions/deposits/gvozdica
Disallow: /ru/person/contributions/deposits/benefit
Disallow: /ru/person/contributions/deposits/no-passport
Disallow: /ru/person/contributions/deposits/record
Disallow: /ru/person/contributions/deposits/onlike
Disallow: /ru/person/contributions/close_deposits/benefit
Disallow: /ru/person/contributions/close_deposits/multi_currency
Disallow: /ru/person/contributions/close_deposits/inter
Disallow: /promo/pobeda6/
Disallow: /promo/gvozdika/
Disallow: /promo/prosto7/
Disallow: /promo/memory
Disallow: /ru/person/bank_cards/debit/newclient
Disallow: /common/img/uploaded/redirected/person/bank_cards/debet/newclient
Disallow: /ru/person/sberkids/faq_parents
Disallow: /ru/person/sberkids/faq_kids
Disallow: /ru/promo/paket_zarplatny
Disallow: /common/img/uploaded/redirected/person/promo/paket_zarplatny/
Disallow: /ru/person/bank_inshure/insuranceprogram/life/dszhkk
Disallow: /dszhkk
Disallow: /ru/support-test
Disallow: /ru/support-test/about_card-test
Disallow: /sms/*
Disallow: /common/img/uploaded/files/sms/*
Disallow: /ru/person/credits/money/consumer

Sitemap: https://www.sberbank.ru/sitemap.xml
