User-agent: *
Disallow: /chat/m/
Disallow: /search/
Disallow: /idea-popup/
Disallow: /x/
Disallow: /i/
Disallow: /*mobileapp=true
Disallow: /*popup=true
Disallow: /widgetembed/
Disallow: /embed-widget/
Disallow: /wiki/static/
Allow: /wiki/static/load.php
Disallow: /badbrowser/
Disallow: /jobs/
Sitemap: https://www.tradingview.com/sitemap.xml