User-agent: *
allow: /
disallow: /search*
disallow: /staticcontent/*
allow: /staticcontent/*.js
allow: /staticcontent/*.css
allow: /staticcontent/*.png
allow: /staticcontent/*.jpg
allow: /staticcontent/*.gif
Sitemap: https://www.zee5.com/sitemap/index.xml
Sitemap: https://www.zee5.com/sitemap/news-en.xml
Sitemap: https://www.zee5.com/sitemap/news-hi.xml
Sitemap: https://www.zee5.com/sitemap/news-bn.xml
Sitemap: https://www.zee5.com/sitemap/news-mr.xml
Sitemap: https://www.zee5.com/sitemap/news-hr.xml
Sitemap: https://www.zee5.com/sitemap/news-ta.xml
Sitemap: https://www.zee5.com/sitemap/news-te.xml
Sitemap: https://www.zee5.com/sitemap/news-pa.xml
Sitemap: https://www.zee5.com/sitemap/news-ml.xml
Sitemap: https://www.zee5.com/sitemap/news-kn.xml
 
Sitemap: https://www.zee5.com/sitemap/news-video-en.xml
Sitemap: https://www.zee5.com/sitemap/news-video-hi.xml
Sitemap: https://www.zee5.com/sitemap/news-video-bn.xml
Sitemap: https://www.zee5.com/sitemap/news-video-mr.xml
Sitemap: https://www.zee5.com/sitemap/news-video-hr.xml
Sitemap: https://www.zee5.com/sitemap/news-video-ta.xml
Sitemap: https://www.zee5.com/sitemap/news-video-te.xml
Sitemap: https://www.zee5.com/sitemap/news-video-pa.xml
Sitemap: https://www.zee5.com/sitemap/news-video-ml.xml
Sitemap: https://www.zee5.com/sitemap/news-video-kn.xml
